### ISSUE TITLE
relative path?

### ISSUE THREAD

**Issue by nevir** [yortus/require-self#11]
I'm wondering if it would make sense for require-self to generate a relative path to the module rather than absolute? That way, the user can move their repo around on disk without having to re-run `require-self`.

**Comment by yortus** [comment]
@nevir it used to be `require('..')`, but was changed in PR #7 to support scoped packages. You could probably still generate a relative path and support both scoped and unscoped packages (eg using `path.relative(...)`. A PR would be welcome, as I'm not actively using this lib atm.

**Comment by yortus** [comment]
Closing as stale.
