### ISSUE TITLE
Does not work with Typescript VSCode intellisense.

### ISSUE THREAD

**Issue by jlguenego** [yortus/require-self#12]
Very useful module. But I cannot make it working with Visual Studio Code Intellisense.
Help appreciated.

**Comment by yortus** [comment]
Hi @jlguenego, sorry for the delay, I haven't looked at this project in a long while. I just added a few lines to the bin script so it should work with TypeScript packages now. Try v0.2.2 (latest) and let me know if it works.

**Comment by yortus** [comment]
Closing as fixed. Feel free to re-open if there are still problems.

**Comment by jlguenego** [comment]
I tested it on my project. It works ! Thanks a lot ;)
The correction you have made is exactly what I was expecting. So now I will remove my custom script and use your module.

Again thanks !

Note: 
My module is node-expose-sspi.
