### ISSUE TITLE
doesn't work w/ scoped references

### ISSUE THREAD

**Issue by benmonro** [yortus/require-self#2]
My module has a name like this: `"name":"@myCompany/my-module"`

in this case require-self should be exporting ../../ instead of just ..

**Comment by benmonro** [comment]
added PR: https://github.com/yortus/require-self/pull/3

**Comment by yortus** [comment]
Thanks @benmonro for raising this, happy to support scoped packages (I haven't used them myself so far).

I think the PR needs a little extra logic (see my comment there) but then I'll be happy to merge it.

**Comment by yortus** [comment]
#7 fixes this.

**Comment by LeMisterV** [comment]
Hi @yortus ,

#7 added a useful support for scoped modules. Would it be possible you publish a new version with this improvement ?

Thx a lot
