### ISSUE TITLE
Using require-self with npm module using Babel

### ISSUE THREAD

**Issue by epsitec** [yortus/require-self#5]
If I try to use `require-self` with Babel or `mocha`, while having `"main"` point to `"lib/index.js"` and using Babel to transpile `./src` to `./lib`, my requires load from `./lib` whereas the source of my tests still sits in `./src`. And this is not what I intend...

I've applied Artem Govorov's suggestion to _patch_ `require()` in order to get my tests running.
- [Blog post with solution for Wallaby.js](http://code.fitness/post/2016/02/npm-require-self-with-wallaby.html)
- [Blog post with solution for mocha](http://code.fitness/post/2016/02/mocha-require-self.html)

Do you see an other way to get `mocha` work with my setup?

**Comment by yortus** [comment]
> my requires load from ./lib whereas the source of my tests still sits in ./src. And this is not what I intend...

Can you clarify why this is not what you intend? I have a similar setup, but with TypeScript so I have `.ts` source files and `.js` transpiled files. Everything works seamlessly thanks to source maps. Do you transpile your test files?

**Comment by epsitec** [comment]
Yes, I am transpiling my source and test files. But somehow with mocha, I get strange errors when I start my tests with:

`"babel -d lib/ src/ && mocha lib/test/**/*.js"`

You can see this for yourself by checking out https://github.com/epsitec-sa/electrum and removing the `--require ./test/test-require-patch.js` from the `test/mocha.opts` file, then launching from the command line:

```
babel -d lib/ src/
mocha lib/test/**/*.js
```

**Comment by yortus** [comment]
I can't get it to install:

```
V:\Projects\oss\electrum>npm install

> radium@0.16.6 postinstall V:\Projects\oss\electrum\node_modules\radium
> cd lib || npm run lib

npm WARN optional dep failed, continuing fsevents@1.0.7
\
> electrum@2.18.2 postinstall V:\Projects\oss\electrum
> require-self


> electrum@2.18.2 prepublish V:\Projects\oss\electrum
> npm run compile


> electrum@2.18.2 compile V:\Projects\oss\electrum
> babel -d lib/ src/

ReferenceError: Unknown plugin "transform-class-properties" specified in "V:\\Projects\\oss\\electrum\\.babelrc" at 2, attempted to resolve relative to "V:\\Projects\\oss\\electrum"
    at V:\Projects\oss\electrum\node_modules\babel-core\lib\transformation\file\options\option-manager.js:206:17
    at Array.map (native)
    at Function.normalisePlugins (V:\Projects\oss\electrum\node_modules\babel-core\lib\transformation\file\options\option-manager.js:182:20)
    at OptionManager.mergeOptions (V:\Projects\oss\electrum\node_modules\babel-core\lib\transformation\file\options\option-manager.js:298:36)
    at OptionManager.addConfig (V:\Projects\oss\electrum\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:10)
    at OptionManager.findConfigs (V:\Projects\oss\electrum\node_modules\babel-core\lib\transformation\file\options\option-manager.js:434:16)
    at OptionManager.init (V:\Projects\oss\electrum\node_modules\babel-core\lib\transformation\file\options\option-manager.js:489:12)
    at File.initOptions (V:\Projects\oss\electrum\node_modules\babel-core\lib\transformation\file\index.js:211:75)
    at new File (V:\Projects\oss\electrum\node_modules\babel-core\lib\transformation\file\index.js:129:22)
    at Pipeline.transform (V:\Projects\oss\electrum\node_modules\babel-core\lib\transformation\pipeline.js:48:16)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! electrum@2.18.2 compile: `babel -d lib/ src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electrum@2.18.2 compile script 'babel -d lib/ src/'.

```

**Comment by epsitec** [comment]
Sorry, fixed that. I somehow left out `babel-plugin-transform-class-properties` from `package.json`.

**Comment by yortus** [comment]
I did a `git pull` and another `npm install`, now I get: `ReferenceError: Unknown plugin "transform-es2015-classes" specified in "V:\\Projects\\oss\\electrum\\.babelrc"` during install.

**Comment by epsitec** [comment]
Just to make sure: I removed `node_modules` and did a fresh `npm install`; everything builds fine.
I also tried to clone https://github.com/epsitec-sa/electrum.git into an empty folder and then `npm install`. It also works.

**Comment by yortus** [comment]
OK I got it working. The error is in your `/test/test-helper.js` file, line 25, where you are using rest parameter syntax. No node version supports this ES6 feature yet (well, only behind a flag).

Try `mocha --harmony lib/test/**/*.js`

EDIT: I also see a spread operator in line 29. Also not supported yet by Node 4.x.

**Comment by epsitec** [comment]
I am running npm v3.5.3, node v5.0.0 on Windows. Upgraded to latest npm v3.7.1. It still works too.

**Comment by epsitec** [comment]
I am developing exclusively on Node 5, so I have not been bitten by these issues.

**Comment by yortus** [comment]
Node 5 also doesn't support rest parameters.

**Comment by yortus** [comment]
Your tests run fine for me with the `--harmony` flag

**Comment by yortus** [comment]
I'd say you need to:
- Add the `transform-es2015-parameters` plugin to your build
- Add the `transform-es2015-spread` plugin to your build
- Avoid ES6 features like rest and spread in `test-helper.js` since it's not transpiled

**Comment by epsitec** [comment]
I am trying to understand what's going on here:
1. The clean repo where I have just cloned electrum and build it with the latest version from GitHub runs all tests successfully.
2. The working repo where I cleaned node_modules and where the source code is identical fails on multiple tests.

I must have some stale files lying around.

**Comment by rom1504** [comment]
if you want to use es6 in your tests, you should use https://babeljs.io/docs/setup/#mocha or just transpile your tests as well

**Comment by epsitec** [comment]
@rom1504 thank you for the tip. I cannot let `mocha` work on my ES6 source (`./src`) because then, the `require-self` points to `./lib` and I get into trouble, having part of the source coming from `./src` and part of it from `./lib`. That's why I started with the idea of redirecting the `require ('electrum')` to require `./src` regardless of `"main"` in `package.json`.

Transpiling the tests as well seems to be the other way to go if I don't want to have to patch the `require()`.

**Comment by epsitec** [comment]
@yortus I had some garbage left over in `./lib` which was interfering with my tests. Now I can successfully run all my tests with `mocha` on the `./lib` output.

Now, back to my original question: if I want to run `mocha` directly on my ES6 code (that is, on `./src`), do you see any other solution than patching `require()` to resolve `electrum` to `./src` instead of `./lib`?

**Comment by yortus** [comment]
I still don't get why you want to run `mocha` against your `/src` rather than your `/lib`. The tests seem to run fine against `/lib`, so why don't you want to do that?

**Comment by yortus** [comment]
Both of the following work for me:

```
mocha --harmony lib/test/**/*.js
mocha --harmony src/test/**/*.js
```

**Comment by epsitec** [comment]
- `mocha --harmony lib/test/**/*.js` works fine (70 passing).
- `mocha --harmony src/test/**/*.js` fails (69 passing, 1 failing).

**Comment by epsitec** [comment]
And I felt that it would be nice to not have to go through the extra step of producing the `./lib` output just to run the tests. But you are right: running the tests on the end artifact is a better idea than trying to run it on the source.

**Comment by epsitec** [comment]
Pull the latests changes and you should see 1 test failing.

**Comment by epsitec** [comment]
When running `mocha` on `./src`, then `require ('electrum')` will pull in `./lib/index.js` which defines a different instance of `Electrum` than what I get if I `require ('./index.js')`. And that's why one of the tests fails (it is setting state on the instance of `Electrum` from `./src` and one of the components, which has been attached to the `Electrum` from `./lib` does not get to see that state).

Constrast `import E from '../index.js';` at line 9 of `./src/test/component.js` with `import Electrum from 'electrum';` at line 2 of `./src/all-components.js`.

**Comment by yortus** [comment]
I see the failing test when running against `/lib`, when there should be just one `Electrum` instance, right?

When I run the tests on `/src`, they all pass.

**Comment by epsitec** [comment]
I see the opposite!? Running tests on `./src` should not work because of the confusion between `./lib` and `./src`.

**Comment by yortus** [comment]
I'm just setting your `"test"` script in `package.json` to `mocha --harmony lib/test/**/*.js`, since I don't usually install anything globally. Then I run `npm test`. I get one failed test. The assertion error is `AssertionError: expected '/Post: true/Author: false' to equal '/Post: true/Content: true/Author: false'`.

**Comment by epsitec** [comment]
I get the error when running `mocha --harmony src/test/**/*.js`. And everything is fine if I `npm test`.

**Comment by yortus** [comment]
I just did a clean install and now get the same results as you. So running the tests in `/lib` is working, and you have figured out why the test fails when running in `/src`. Is this setup okay for you (ie testing against `/lib`)?

**Comment by epsitec** [comment]
It will do, yes. Thank you for the discussion and your insights.

**Comment by epsitec** [comment]
I summarized this discussion in an edit to http://code.fitness/post/2016/02/mocha-require-self.html

**Comment by yortus** [comment]
Okay great. BTW I don't recommend publishing with the `--harmony` flag, that was just a quickfix to help diagnose the problem. It won't work for people using node 0.12 (which is still in active LTS), and just generally some people might not want to run 3rd party code that switches on V8's 'experimental' flag. 

I mentioned what I think is a better approach in an earlier comment - https://github.com/yortus/require-self/issues/5#issuecomment-182852026
