### ISSUE TITLE
Publish new version with scoped modules support

### ISSUE THREAD

**Issue by LeMisterV** [yortus/require-self#8]
Hi @yortus ,

#7 added a useful support for scoped modules. Would it be possible you publish a new version with this improvement ?

Thx a lot
(sorry for duplicated message)

**Comment by yortus** [comment]
Hi @LeMisterV, 

Of course - just published v0.2.0. Sorry I forgot to do it earlier.

**Comment by LeMisterV** [comment]
Thanks a lot !
