### ISSUE TITLE
about prepublish script and changing behaviour

### ISSUE THREAD

**Issue by LeMisterV** [yortus/require-self#9]
Hi,

As explained [in NPM doc](https://docs.npmjs.com/misc/scripts#prepublish-and-prepare), prepublish script will soon change a little.
Having this in mind, I wonder if you should change the readme file to add require-self to postInstall or prepare hook instead of prepublish ?
I think the most common use would be postInstall, what do you feel about that ?

**Comment by AviVahl** [comment]
wouldn't the `postinstall` script run for packages **installing my package**, if I'm a library that uses require-self? that's not good if I have it in my devDeps.

is `prepare` supported in npm2/3?

**Comment by yortus** [comment]
Good point that this needs to be changed @LeMisterV.

@AviVahl you are right about `postinstall`, so that would not be advisable in general. `prepare` seems to be the best option, although it will only be run by npm on `npm install` when the developer is using npm4 and higher. For those using npm3 or lower, they will have to manually run `npm run prepare` after running `npm install`.

I'll change the README accordingly. What do you think? Does that resolve the issue?

**Comment by AviVahl** [comment]
Node 6 is still LTS, and uses npm3, so I'm not sure of the correct approach here myself.
We use it here in production environments, so having to manually run a command (especially when packages are being auto tested by a CI) is less likely to be the chosen approach.
With yarn in the mix (and whatever "compatible" way they chose to handle npm lifecycle scripts), it gets even more complex.

I basically need a lifecycle script that works with npm3-5/yarn, that is run automatically at the end of `npm i` or `yarn`, and only happens in dev mode (=not when others install my package). I'm not sure if such exists with all the npm behavior changes and how yarn handles scripts.

**Comment by LeMisterV** [comment]
We're just talking about the README content here...
Maybe the best solution is just to warn about this issue and give different solutions depending on npm version used as talked in this thread...

**Comment by AviVahl** [comment]
People actually read the `README` to decide how such a tool should be integrated, so it also has some importance I'd say. :)

Warning about possible behavioral changes of different npm versions might be the best approach.

**Comment by yortus** [comment]
How about the following guidance:
- Use `prepare` for npm >=4
- Use `prepublish` for npm <4 and yarn

If anyone wants to come up with some helpful wording for the README, please feel free.

**Comment by yortus** [comment]
Another wrinkle I've noticed with npm 5 is that it deletes the files placed in the `node_modules` folder whenever installing new modules (and possibly during other operations too).
